language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

services: mysql

env:
  - DJANGO_VERSION=2.1.13
  - DJANGO_VERSION=2.2.6

install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install

before_script:
  - mysql -e 'create database travis_ci_db;'
  - python manage.py syncdb --noinput

script:
  - python manage.py test
  - python manage.py runserver